Version 4
SymbolType CELL
RECTANGLE Normal -96 -81 96 96
WINDOW 0 0 -89 Bottom 2
SYMATTR SpiceModel AM
PIN -96 0 LEFT 8
PINATTR PinName ADSR_shape
PINATTR SpiceOrder 1
PIN 0 96 VLEFT 8
PINATTR PinName GND
PINATTR SpiceOrder 2
PIN 96 -48 RIGHT 8
PINATTR PinName OUT
PINATTR SpiceOrder 3
PIN -96 -48 LEFT 8
PINATTR PinName Signal
PINATTR SpiceOrder 4
PIN -64 96 VLEFT 8
PINATTR PinName V+
PINATTR SpiceOrder 5
PIN 64 96 VLEFT 8
PINATTR PinName V-
PINATTR SpiceOrder 6
